#!/usr/bin/env python

"""test.py: Test input."""

__author__ = "Joel DeRouchey"
__copyright__ = "No Copyright 2017, Reno, Nevada"


import datetime, time
then = datetime.datetime.now() #+ datetime.timedelta(seconds=10)
# while then > datetime.datetime.now():
#    print 'sleeping'
#    time.sleep(1)
your_name = raw_input('Enter your name:')
now = datetime.datetime.now()
print "Welcome to python " + your_name + "."
print then
print now
print now - then

